### ISSUE TITLE
Running the demo on a remote server

### ISSUE THREAD

**Issue by dgorczyca** [OpenVidu/classroom-demo#3]
Hi guys,

Thanks for sharing your great work!
I have tried getting your demo to work remotely, with nginx server in front of spring boot, everything runs fine except video :/
Here is my simple nginx conf (for others for future reference)

    server {
        listen 80;
        server_name mydomain.com;
        return 301 https://$host$request_uri;
    }
    server {
    listen 443 ssl;
    server_name mydomain.com;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA256:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EDH+aRSA+AESGCM:EDH+aRSA+SHA256:EDH+aRSA:EECDH:!aNULL:!eNULL:!MEDIUM:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SEED";

    add_header Strict-Transport-Security "max-age=31536000";

    ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;

    location / {
        ssi on;

        proxy_pass https://localhost:5000/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;

    }
    }
`

I modified the mysql password and openvidu.url in my application.properties (it points by default to https://localhost:4443/, I changed it to https://mydomain.com:4443/)

I was hoping this was going to be enough, unfortunately I am getting an error in the browser console (Chrome):
 

> wss://localhost:4443?sessionId=yisxttewks2rf3yv&token=j6y1cnxicdqcdmwl&role=PUBLISHER
> webSocketWithReconnection.js:22 WebSocket connection to 'wss://localhost:4443/openvidu' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

I am not sure where does the Angular app takes the localhost:4443 value from, could you point out what other steps would be necessary to get it to run remotely please?

**Comment by pabloFuente** [comment]
Hi!

You have to configure your public URL in OpenVidu Server. I don't know how you have deployed it, but you must specify in the launching command the following property:

`openvidu.publicurl=https://YOU_PUBLIC_IP_OR_DOMAIN:4443/`

That way OpenVidu Server can tell your clients where to connect their WebSocket.

**Comment by dgorczyca** [comment]
Thank you @pabloFuente !
Your comment allowed me to move forward. The way I am running the OpenVidu server is as described in the [demo tutorial](https://openvidu.io/docs/demos/openvidu-classroom/) - using docker:
`docker run -p 4443:4443 --rm -e openvidu.publicurl=https://domain:4443/ -e spring.datasource.username=root -e spring.datasource.password=password -e openvidu.secret=MY_SECRET openvidu/openvidu-server-kms:2.4.0`

I now need to adjust the nginx configuration to proxy the web sockets, here is what I have done so far, might not be right though:
`
    server {
        listen 443 ssl;
        ...
       location /openvidu {

           proxy_pass http://localhost:4443;
           proxy_http_version 1.1;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection "upgrade";
           proxy_read_timeout 86400;
    }
`

I am now getting this error in the browser console (after starting a session as a teacher)

> Could not connect to wss://domain.com:4443/openvidu (invoking onerror if defined)

I can see the request makes it to logs where I run docker, let me investigate a bit further whether the above is forwarding web sockets traffic correctly, will post back full nginx configuration and steps that once it works for me let's keep this issue open till the next comment please...

**Comment by dgorczyca** [comment]
OK, so after checking the IP tables I realised I didn't need to proxy web sockets.
What I was missing was modifying my TLS/SSL certificates from letsencrypt converted into Java Key Store format 
`openssl pkcs12 -export -in fullchain.pem -inkey privkey.pem -out keystore.p12 -name keyName` 
and then following example here [openvidu using your own certificate](https://openvidu.io/docs/deployment/custom-certificate/) I run the server:
`docker run -p 4443:4443 --rm -v /root/classroom-demo/keystore.p12:/keystore.p12 -e openvidu.publicurl=https://mydomain.com:4443/ -e openvidu.secret=MY_SECRET -e server.ssl.key-store=/keystore.p12 -e server.ssl.key-store-password=keyPassword -e server.ssl.key-alias=keyName openvidu/openvidu-server-kms:2.4.0`
And now I thought everything worked, unfortunately it didn't - when I logged in as a teacher (tried multiple browsers) and someone else on another computer logged in as a student (afterwards we swapped), we were both able to get on to the same lesson url, but the student was never asked to use their camera and they were unable to see the video of a tutor. Really disappointing, there were no errors in the browser console.

If anyone has an idea what was missing please let me know, otherwise feel free to close this ticket.

**Comment by pabloFuente** [comment]
Hi,

In this demo student's do not publish their webcam. They only subscribe to teacher's media streams.

And if your teacher video is not being received by other users connected to the session, that usually means you lack a TURN server. The entire process of deploying OpenVidu in your own Ubuntu server is explained in [OpenVidu Deployment](https://openvidu.io/docs/deployment/deploying-ubuntu/) section.

**Comment by ghost** [comment]
Hi,
I am new to OpenVidu and I am trying to run OpenVidu demo on my server.
when I was trying to creating meeting I am getting this error
I am getting below error and I am not going to further step
please help me how to solve below error

webSocketWithReconnection.js:161 WebSocket connection to 'wss://localhost:4443/openvidu' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Below I attached a snapshot of I am getting the error.

![Screenshot_2](https://user-images.githubusercontent.com/45309411/62194498-98699280-b397-11e9-8621-03f6d6c276b3.png)
 
Thanks.

**Comment by pabloFuente** [comment]
You must follow instructions to deploy OpenVidu on your server. You have not properly completed this step: https://openvidu.io/docs/deployment/deploying-ubuntu/#8-init-openvidu-server-jar-executable.

You have not set property `openvidu.publicurl` in your openvidu-server

```
-Dopenvidu.publicurl=https://YOUR_OOPENVIDU_SERVER_PUBLIC_IP:4443/
```

**Comment by ghost** [comment]
Hi @pabloFuente,
if I am running this command I am getting below error
please help me how to solve this error.
below command, I am running
java -jar -Dopenvidu.secret=12345 -Dopenvidu.publicurl=https://mydomain.com:4443/ openvidu-server-2.9.0.jar
 and I am getting below error

Error: Unable to access jarfile openvidu-server-2.9.0.jar

Thanks.

**Comment by pabloFuente** [comment]
You don't have an `openvidu-server-2.9.0.jar` file in the path of your command....

**Comment by ghost** [comment]
No,
I don't have this file opened-server-2.9.0.jar.
how to download it?
please help me
thanks.

**Comment by pabloFuente** [comment]
Just follow instructions: https://openvidu.io/docs/deployment/deploying-ubuntu/

**Comment by ghost** [comment]
Thanks for your support. 
now it is working fine, Previously  I didn't set up properly.

Thanks, @pabloFuente

**Comment by code-mentor7** [comment]
Hello. @pabloFuente 
Already I deployed the OpenVidu Pro to AWS.
Now OpenVidu default port 4443 is used.
But I am going to use HTTPS 443 common port.
How can I do?

Please advice.
Thank you.

**Comment by sernocturno** [comment]
> 
> 
> Hello. @pabloFuente
> Already I deployed the OpenVidu Pro to AWS.
> Now OpenVidu default port 4443 is used.
> But I am going to use HTTPS 443 common port.
> How can I do?
> 
> Please advice.
> Thank you.

here you have a complete list of parameters for openvidu [https://docs.openvidu.io/en/2.12.0/reference-docs/openvidu-server-params/](url)

 yo have to add `-Dserver.port=443` to your java command

**Comment by micaelgallego** [comment]
I recommend you to deploy 2.13 version (latest in the moment of writing this)

**Comment by sayantandey** [comment]
I resolved this by signing to openvidu dashboard, then testing the connection and generating a new wss token
