### ISSUE TITLE
Error connecting client to server 

### ISSUE THREAD

**Issue by designerprasan007** [OpenVidu/classroom-demo#5]
here is the command i use to up the docker

>   docker run -p 4443:4443 -e openvidu.publicurl=https://dev.conitor.in:4443/ openvidu/openvidu-server-kms:2.11.0
and to run angular code i'm using this command 

> ng s --host 165.227.13.44 --ssl true

the error i'm getting when  i connect to remote server.

> vendor.js:69943 ERROR HttpErrorResponse {headers: HttpHeaders, status: 409, statusText: "OK", url: "https://165.227.13.44:4443/api/sessions", ok: false, …}
defaultErrorLogger @ vendor.js:69943
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ vendor.js:69991
next @ vendor.js:88943
schedulerFn @ vendor.js:86197
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ vendor.js:179077
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ vendor.js:179015
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ vendor.js:178961
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ vendor.js:178938
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ vendor.js:178704
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ vendor.js:86181
(anonymous) @ vendor.js:88467
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.js:6239
push../node_modules/zone.js/dist/zone.js.Zone.run @ polyfills.js:5998
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ vendor.js:88404
onHandleError @ vendor.js:88467
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ polyfills.js:6243
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ polyfills.js:6046
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ polyfills.js:6346
ZoneTask.invoke @ polyfills.js:6335
timer @ polyfills.js:8918
setTimeout (async)
scheduleTask @ polyfills.js:8939
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.js:6258
onScheduleTask @ polyfills.js:6149
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.js:6252
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ polyfills.js:6086
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask @ polyfills.js:6109
scheduleMacroTaskWithCurrentZone @ polyfills.js:7042
(anonymous) @ polyfills.js:8954
proto.<computed> @ polyfills.js:7366
hostReportError @ vendor.js:189199
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.error @ vendor.js:179049
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._error @ vendor.js:178964
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.error @ vendor.js:178944
push../node_modules/rxjs/_esm5/internal/OuterSubscriber.js.OuterSubscriber.notifyError @ vendor.js:178455
push../node_modules/rxjs/_esm5/internal/InnerSubscriber.js.InnerSubscriber._error @ vendor.js:178154
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.error @ vendor.js:178944
(anonymous) @ vendor.js:180924
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe @ vendor.js:178320
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178306
subscribeToResult @ vendor.js:189720
push../node_modules/rxjs/_esm5/internal/operators/catchError.js.CatchSubscriber.error @ vendor.js:182010
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._error @ vendor.js:178964
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.error @ vendor.js:178944
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._error @ vendor.js:178964
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.error @ vendor.js:178944
push../node_modules/rxjs/_esm5/internal/OuterSubscriber.js.OuterSubscriber.notifyError @ vendor.js:178455
push../node_modules/rxjs/_esm5/internal/InnerSubscriber.js.InnerSubscriber._error @ vendor.js:178154
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.error @ vendor.js:178944
onLoad @ vendor.js:34988
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6271
onInvokeTask @ vendor.js:88436
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6270
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ polyfills.js:6043
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ polyfills.js:6346
invokeTask @ polyfills.js:7541
globalZoneAwareCallback @ polyfills.js:7578
load (async)
customScheduleGlobal @ polyfills.js:7680
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.js:6258
onScheduleTask @ polyfills.js:6149
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.js:6252
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ polyfills.js:6086
push../node_modules/zone.js/dist/zone.js.Zone.scheduleEventTask @ polyfills.js:6112
(anonymous) @ polyfills.js:7851
(anonymous) @ vendor.js:35061
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe @ vendor.js:178320
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178306
subscribeToResult @ vendor.js:189720
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._innerSub @ vendor.js:184254
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext @ vendor.js:184248
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next @ vendor.js:184231
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ vendor.js:178938
(anonymous) @ vendor.js:189584
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe @ vendor.js:178320
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178306
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call @ vendor.js:184209
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178301
push../node_modules/rxjs/_esm5/internal/operators/filter.js.FilterOperator.call @ vendor.js:183396
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178301
push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call @ vendor.js:183957
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178301
push../node_modules/rxjs/_esm5/internal/operators/catchError.js.CatchOperator.call @ vendor.js:181985
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178301
(anonymous) @ main.js:2383
ZoneAwarePromise @ polyfills.js:6779
push../src/app/shared/services/open-vidu.service.ts.OpenViduService.createSession @ main.js:2369
(anonymous) @ main.js:2358
ZoneAwarePromise @ polyfills.js:6779
push../src/app/shared/services/open-vidu.service.ts.OpenViduService.getToken @ main.js:2355
(anonymous) @ main.js:3011
ZoneAwarePromise @ polyfills.js:6779
push../src/app/video-room/video-room.component.ts.VideoRoomComponent.getToken @ main.js:3009
(anonymous) @ main.js:2830
push../src/app/video-room/video-room.component.ts.VideoRoomComponent.connectToSession @ main.js:2825
push../src/app/video-room/video-room.component.ts.VideoRoomComponent.joinToSession @ main.js:2581
(anonymous) @ main.js:2555
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6271
onInvokeTask @ vendor.js:88436
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6270
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ polyfills.js:6043
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ polyfills.js:6346
ZoneTask.invoke @ polyfills.js:6335
timer @ polyfills.js:8918
setTimeout (async)
scheduleTask @ polyfills.js:8939
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.js:6258
onScheduleTask @ polyfills.js:6149
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.js:6252
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ polyfills.js:6086
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask @ polyfills.js:6109
scheduleMacroTaskWithCurrentZone @ polyfills.js:7042
(anonymous) @ polyfills.js:8954
proto.<computed> @ polyfills.js:7366
push../src/app/video-room/video-room.component.ts.VideoRoomComponent.initApp @ main.js:2550
push../src/app/video-room/video-room.component.ts.VideoRoomComponent.toggleDialogChooseRoom @ main.js:2724
eval @ VideoRoomComponent.html:7
handleEvent @ vendor.js:91437
callWithDebugContext @ vendor.js:92507
debugHandleEvent @ vendor.js:92234
dispatchEvent @ vendor.js:82181
(anonymous) @ vendor.js:83384
schedulerFn @ vendor.js:86209
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ vendor.js:179077
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ vendor.js:179015
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ vendor.js:178961
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ vendor.js:178938
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ vendor.js:178704
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ vendor.js:86181
push../src/app/shared/components/dialog-choose-room/dialog-choose-room.component.ts.DialogChooseRoomComponent.accept @ main.js:832
eval @ DialogChooseRoomComponent.html:162
handleEvent @ vendor.js:91437
callWithDebugContext @ vendor.js:92507
debugHandleEvent @ vendor.js:92234
dispatchEvent @ vendor.js:82181
(anonymous) @ vendor.js:90646
(anonymous) @ vendor.js:153224
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6271
onInvokeTask @ vendor.js:88436
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6270
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ polyfills.js:6043
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ polyfills.js:6346
invokeTask @ polyfills.js:7541
globalZoneAwareCallback @ polyfills.js:7567
Show 111 more frames
main.js:2406 {id: "wss://dev.conitor.in:4443?sessionId=prasanna&token=ogmrth5tv3q14aqx&role=PUBLISHER&version=2.11.0", session: "prasanna", role: "PUBLISHER", data: "", token: "wss://dev.conitor.in:4443?sessionId=prasanna&token=ogmrth5tv3q14aqx&role=PUBLISHER&version=2.11.0"}
vendor.js:169929 openvidu-server version: 2.11.0
vendor.js:172669 WebSocket connection to 'wss://dev.conitor.in:4443/openvidu' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID
WebSocketWithReconnection @ vendor.js:172669
JsonRpcClient @ vendor.js:172490
push../node_modules/openvidu-browser/lib/OpenVidu/OpenVidu.js.OpenVidu.startWs @ vendor.js:168182
(anonymous) @ vendor.js:169762
ZoneAwarePromise @ polyfills.js:6779
push../node_modules/openvidu-browser/lib/OpenVidu/Session.js.Session.connectAux @ vendor.js:169761
(anonymous) @ vendor.js:168992
ZoneAwarePromise @ polyfills.js:6779
push../node_modules/openvidu-browser/lib/OpenVidu/Session.js.Session.connect @ vendor.js:168983
push../src/app/video-room/video-room.component.ts.VideoRoomComponent.connect @ main.js:2849
(anonymous) @ main.js:2831
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.js:6239
onInvoke @ vendor.js:88445
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.js:6238
push../node_modules/zone.js/dist/zone.js.Zone.run @ polyfills.js:5998
(anonymous) @ polyfills.js:6758
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6271
onInvokeTask @ vendor.js:88436
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6270
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ polyfills.js:6043
drainMicroTaskQueue @ polyfills.js:6449
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ polyfills.js:6350
invokeTask @ polyfills.js:7541
globalZoneAwareCallback @ polyfills.js:7578
vendor.js:172678 Could not connect to wss://dev.conitor.in:4443/openvidu (invoking onerror if defined) Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
WebSocketWithReconnection.ws.onerror @ vendor.js:172678
wrapFn @ polyfills.js:7129
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6271
onInvokeTask @ vendor.js:88436
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6270
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ polyfills.js:6043
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ polyfills.js:6346
invokeTask @ polyfills.js:7541
globalZoneAwareCallback @ polyfills.js:7567
error (async)
customScheduleGlobal @ polyfills.js:7680
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.js:6258
onScheduleTask @ polyfills.js:6149
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.js:6252
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ polyfills.js:6086
push../node_modules/zone.js/dist/zone.js.Zone.scheduleEventTask @ polyfills.js:6112
(anonymous) @ polyfills.js:7851
desc.set @ polyfills.js:7190
WebSocketWithReconnection @ vendor.js:172677
JsonRpcClient @ vendor.js:172490
push../node_modules/openvidu-browser/lib/OpenVidu/OpenVidu.js.OpenVidu.startWs @ vendor.js:168182
(anonymous) @ vendor.js:169762
ZoneAwarePromise @ polyfills.js:6779
push../node_modules/openvidu-browser/lib/OpenVidu/Session.js.Session.connectAux @ vendor.js:169761
(anonymous) @ vendor.js:168992
ZoneAwarePromise @ polyfills.js:6779
push../node_modules/openvidu-browser/lib/OpenVidu/Session.js.Session.connect @ vendor.js:168983
push../src/app/video-room/video-room.component.ts.VideoRoomComponent.connect @ main.js:2849
(anonymous) @ main.js:2831
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.js:6239
onInvoke @ vendor.js:88445
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.js:6238
push../node_modules/zone.js/dist/zone.js.Zone.run @ polyfills.js:5998
(anonymous) @ polyfills.js:6758
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6271
onInvokeTask @ vendor.js:88436
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6270
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ polyfills.js:6043
drainMicroTaskQueue @ polyfills.js:6449
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ polyfills.js:6350
invokeTask @ polyfills.js:7541
globalZoneAwareCallback @ polyfills.js:7578
load (async)
customScheduleGlobal @ polyfills.js:7680
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.js:6258
onScheduleTask @ polyfills.js:6149
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.js:6252
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ polyfills.js:6086
push../node_modules/zone.js/dist/zone.js.Zone.scheduleEventTask @ polyfills.js:6112
(anonymous) @ polyfills.js:7851
(anonymous) @ vendor.js:35061
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe @ vendor.js:178320
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178306
subscribeToResult @ vendor.js:189720
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._innerSub @ vendor.js:184254
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext @ vendor.js:184248
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next @ vendor.js:184231
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ vendor.js:178938
(anonymous) @ vendor.js:189584
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe @ vendor.js:178320
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178306
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call @ vendor.js:184209
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178301
push../node_modules/rxjs/_esm5/internal/operators/filter.js.FilterOperator.call @ vendor.js:183396
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178301
push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call @ vendor.js:183957
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178301
push../node_modules/rxjs/_esm5/internal/operators/catchError.js.CatchOperator.call @ vendor.js:181985
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178301
(anonymous) @ main.js:2405
ZoneAwarePromise @ polyfills.js:6779
push../src/app/shared/services/open-vidu.service.ts.OpenViduService.createToken @ main.js:2391
(anonymous) @ main.js:2360
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.js:6239
onInvoke @ vendor.js:88445
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.js:6238
push../node_modules/zone.js/dist/zone.js.Zone.run @ polyfills.js:5998
(anonymous) @ polyfills.js:6758
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6271
onInvokeTask @ vendor.js:88436
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6270
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ polyfills.js:6043
drainMicroTaskQueue @ polyfills.js:6449
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ polyfills.js:6350
invokeTask @ polyfills.js:7541
globalZoneAwareCallback @ polyfills.js:7578
load (async)
customScheduleGlobal @ polyfills.js:7680
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.js:6258
onScheduleTask @ polyfills.js:6149
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.js:6252
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ polyfills.js:6086
push../node_modules/zone.js/dist/zone.js.Zone.scheduleEventTask @ polyfills.js:6112
(anonymous) @ polyfills.js:7851
(anonymous) @ vendor.js:35061
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe @ vendor.js:178320
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178306
subscribeToResult @ vendor.js:189720
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._innerSub @ vendor.js:184254
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext @ vendor.js:184248
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next @ vendor.js:184231
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ vendor.js:178938
(anonymous) @ vendor.js:189584
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe @ vendor.js:178320
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178306
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call @ vendor.js:184209
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178301
push../node_modules/rxjs/_esm5/internal/operators/filter.js.FilterOperator.call @ vendor.js:183396
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178301
push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call @ vendor.js:183957
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178301
push../node_modules/rxjs/_esm5/internal/operators/catchError.js.CatchOperator.call @ vendor.js:181985
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ vendor.js:178301
(anonymous) @ main.js:2383
ZoneAwarePromise @ polyfills.js:6779
push../src/app/shared/services/open-vidu.service.ts.OpenViduService.createSession @ main.js:2369
(anonymous) @ main.js:2358
ZoneAwarePromise @ polyfills.js:6779
push../src/app/shared/services/open-vidu.service.ts.OpenViduService.getToken @ main.js:2355
(anonymous) @ main.js:3011
ZoneAwarePromise @ polyfills.js:6779
push../src/app/video-room/video-room.component.ts.VideoRoomComponent.getToken @ main.js:3009
(anonymous) @ main.js:2830
push../src/app/video-room/video-room.component.ts.VideoRoomComponent.connectToSession @ main.js:2825
push../src/app/video-room/video-room.component.ts.VideoRoomComponent.joinToSession @ main.js:2581
(anonymous) @ main.js:2555
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6271
onInvokeTask @ vendor.js:88436
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6270
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ polyfills.js:6043
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ polyfills.js:6346
ZoneTask.invoke @ polyfills.js:6335
timer @ polyfills.js:8918
setTimeout (async)
scheduleTask @ polyfills.js:8939
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.js:6258
onScheduleTask @ polyfills.js:6149
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.js:6252
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ polyfills.js:6086
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask @ polyfills.js:6109
scheduleMacroTaskWithCurrentZone @ polyfills.js:7042
(anonymous) @ polyfills.js:8954
proto.<computed> @ polyfills.js:7366
push../src/app/video-room/video-room.component.ts.VideoRoomComponent.initApp @ main.js:2550
push../src/app/video-room/video-room.component.ts.VideoRoomComponent.toggleDialogChooseRoom @ main.js:2724
eval @ VideoRoomComponent.html:7
handleEvent @ vendor.js:91437
callWithDebugContext @ vendor.js:92507
debugHandleEvent @ vendor.js:92234
dispatchEvent @ vendor.js:82181
(anonymous) @ vendor.js:83384
schedulerFn @ vendor.js:86209
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ vendor.js:179077
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ vendor.js:179015
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ vendor.js:178961
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ vendor.js:178938
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ vendor.js:178704
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ vendor.js:86181
push../src/app/shared/components/dialog-choose-room/dialog-choose-room.component.ts.DialogChooseRoomComponent.accept @ main.js:832
eval @ DialogChooseRoomComponent.html:162
handleEvent @ vendor.js:91437
callWithDebugContext @ vendor.js:92507
debugHandleEvent @ vendor.js:92234
dispatchEvent @ vendor.js:82181
(anonymous) @ vendor.js:90646
(anonymous) @ vendor.js:153224
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6271
onInvokeTask @ vendor.js:88436
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.js:6270
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ polyfills.js:6043
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ polyfills.js:6346
invokeTask @ polyfills.js:7541
globalZoneAwareCallback @ polyfills.js:7567
Show 139 more frames
vendor.js:168230 Websocket connection lost (reconnecting)
![Screenshot from 2019-12-16 11-12-22](https://user-images.githubusercontent.com/50103756/70882695-90cd2200-1ff6-11ea-92b6-93a1fe9a2dd3.png)

**Comment by micaelgallego** [comment]
You have to connect to the server using a valid certificate.

If you don't have one, you should open https://dev.conitor.in:4443/ in your browser and accept it.

**Comment by designerprasan007** [comment]
hi micaelgallego thank you for your respons when i opened https://dev.conitor.in:4443/ i got a alert of asking openvidu secret and username i entered OPENVIDUAPP as username and MY_SECRET as secret. now the frontend page is opened. but here i'm getting this message 

> KMS event [IceComponentStateChange]: -> endpoint: xmlmoclhctefvvxk_CAMERA_EAJLX (publisher) | state: FAILED | componentId: 1 | streamId: 1 | timestamp: 1576484598363.


camera is on but cant able to see anything

**Comment by designerprasan007** [comment]
here is the link 
![Screenshot from 2019-12-16 13-55-53](https://user-images.githubusercontent.com/50103756/70890829-faa3f680-200b-11ea-852a-4200d5d202c1.png)
[https://dev.conitor.in:4443/#/ ]()

**Comment by pabloFuente** [comment]
This is probably caused by a networking issue. If you are trying to serve OpenVidu to be accessible from other networks using the Docker container, that is not really contemplated. OpenVidu Docker container is meant to be used for development inside one network. You can try to serve the ddocker container in network `host` mode and see if it solves the issu efor your very particular case.

But again, in a production environment deploying with the Docker container is not officially supported.

**Comment by designerprasan007** [comment]
hi pabloFuente. is their any other solution to overcome this?

**Comment by pabloFuente** [comment]
Yes, the solution is to deploy OpenVidu in production is as stated in the documentation: https://openvidu.io/docs/home/ (Section "Deployment")

**Comment by designerprasan007** [comment]
okay. I will check it and let you know asp.. and I'm heartily thankful you for your response

**Comment by designerprasan007** [comment]
hey. is that enough of deploying code in aws instance or we have to create stack? coz now already I deployed code in aws instance and still getting the same error. and the stack is having a billing cycle.

**Comment by designerprasan007** [comment]
hi. as you suggested i deployed my code in aws with new instance. but still getting the same error as before i showed in image. can you please guide me to overcome this. i had tried the link you given.
![error](https://user-images.githubusercontent.com/50103756/71713133-6cfb4000-2e2e-11ea-841f-4e9dd9294638.jpeg).

**Comment by micaelgallego** [comment]
The error you are obtaining is because you are not using a valid SSL certificate in https. For WebRTC is mandatory to have https connections.

You need to purchase a web domain (like mywebpage.com) and then generate a valid SSL certificate. For example, you can use Let's Encrypt to obtain a SSL certificate for free.

**Comment by designerprasan007** [comment]
i have my domain the domain link is 

> https://streaming.liveonline4u.com:8083/. 

you can check it it's completely secured with https

**Comment by micaelgallego** [comment]
If you have a valid domain, please follow carefully this documentation page to deploy in AWS creating a certificate with Let's Encrypt:

https://openvidu.io/docs/deployment/deploying-aws/

Note that you will need an ElasticIP created beforehand and associate it to a domain (or subdomain) in your DNS provider.

**Comment by designerprasan007** [comment]
okay. let me try with aws stack.

**Comment by designerprasan007** [comment]
hi sir i followed the steps as you given in the link. untill the .jar file evrything was fine but when i run the command 

> java` -jar -Dopenvidu.secret=MY_SECRET -Dopenvidu.publicurl=https:3.20.84.76:4443/ /opt/openvidu/openvidu-server.jar..
i'm getting an error of 

> [ERROR] 2020-01-04 05:26:57,280 [main] org.springframework.boot.SpringApplication (reportFailure) - Application run failed
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.kurento.jsonrpc.internal.server.config.JsonRpcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'openViduServer': Invocation of init method failed; nested exception is java.lang.NullPointerException
![Screenshot from 2020-01-04 10-58-22](https://user-images.githubusercontent.com/50103756/71760315-9f19aa00-2ee1-11ea-90b1-0bd466888c5e.png)



and the image is also attached with this. i followed steps as you shown in the openvidu aws and openvidu deploy ubuntu. please let me know where i'm making mistake. and guide to solve it

**Comment by designerprasan007** [comment]
all ports are running as i said
![Screenshot from 2020-01-04 11-04-07](https://user-images.githubusercontent.com/50103756/71760332-0df70300-2ee2-11ea-918f-58bdf1a9181a.png)

**Comment by designerprasan007** [comment]
i found the issue. you can close it now.
