### ISSUE TITLE
No teacher film for student?

### ISSUE THREAD

**Issue by redskate** [OpenVidu/classroom-demo#6]
Hello

thank you for putting this nice app on github.
After succesfull openvidu installation I could install and start the app.

Where did I install the app:   inside a virtualBox-Ubuntu18 instance running on a mac mini. Firewall opened as needed, openvidu test OK.

Browser is latest Firefox on OSX. I could add a "lesson" title and start.
The app requests CAMERA&MICRO and shows for the teacher's side the camera content.

On the student side (another computer, Firefox on OSX) - the student enters the lesson and sees NOTHING.

Without having yet considered the nice code, I was expecting the student side sees the teacher ... and apparently this demo seems indeed different from the pictures you published on https://openvidu.io/ - did I understand something wrong?

This seems to be the start of an application (a nice framework) but far away from what you shows on the https://openvidu.io/ site. 

A "full" web app, but an incomplete classroom app? I guess not ... so 

very grateful for any hint
Thank you
Regards

**Comment by pabloFuente** [comment]
How are you trying to connect both computers? Are they connected to the same network? How did you configured OpenVidu Server for OpenVidu Classroom app to work?

You can check this same demo app properly deployed here: https://demos.openvidu.io/classroom/#/

**Comment by redskate** [comment]
Computer1 and Computer2 are in the same network.
The configuration is over an external IP.

https://31.27.148.198:4443 is running.

The config file - I will send it to you privately.
Thanks

**Comment by redskate** [comment]
Now I tested with both computers on different networks (one via mobile hotspot) - same story. I sent you the config file privately. 

I discovered under main/resources further property files - I guess I should customize all of them, not only application.properties ... ?

**Comment by redskate** [comment]
https://demos.openvidu.io/classroom/#/ functions indeed (thank you). Mine does not.
Anyway there when the teacher steps back (exits) the lesson, a security dialogue appears asking for some credentials (I guess for openvidu) ... working as intended.
